# Generated by Django 2.2.7 on 2020-06-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='assunto',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
