# Generated by Django 2.2.7 on 2020-06-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contato_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='slug',
            field=models.SlugField(default='boas-vindas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ladies',
            name='biografia',
            field=models.TextField(),
        ),
    ]
