# Generated by Django 2.2.7 on 2020-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200621_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ladies',
            name='blog_pessoal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ladies',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ladies',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ladies',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ladies',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ladies',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
