# Generated by Django 2.2.7 on 2020-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200621_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladies',
            name='foto',
            field=models.ImageField(default=1, upload_to='ladies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='publicacoes'),
        ),
    ]
